import pandas as pd

def carrega_base_dados(base_path):
    return pd.read_csv(
        base_path,
        usecols=['NU_ANO_CENSO', 'NO_UF', 'SG_UF', 'CO_UF', 'NO_MUNICIPIO', 'CO_MUNICIPIO', 'NO_ENTIDADE',
                 'CO_ENTIDADE', 'TP_DEPENDENCIA', 'TP_LOCALIZACAO','IN_AGUA_REDE_PUBLICA', 'IN_AGUA_POCO_ARTESIANO', 'IN_AGUA_CACIMBA',
                 'IN_AGUA_FONTE_RIO', 'IN_AGUA_INEXISTENTE', 'IN_ENERGIA_REDE_PUBLICA', 'IN_ENERGIA_GERADOR_FOSSIL',
                 'IN_ENERGIA_RENOVAVEL', 'IN_ENERGIA_INEXISTENTE', 'IN_ESGOTO_REDE_PUBLICA', 'IN_ESGOTO_FOSSA_SEPTICA',
                 'IN_ESGOTO_FOSSA_COMUM', 'IN_ESGOTO_INEXISTENTE', 'IN_BANHEIRO', 'IN_BANHEIRO_EI',
                 'IN_BANHEIRO_PNE', 'IN_BANHEIRO_FUNCIONARIOS', 'IN_BANHEIRO_CHUVEIRO', 'IN_COZINHA', 'IN_DESPENSA',
                 'IN_AREA_VERDE', 'IN_AUDITORIO', 'IN_BIBLIOTECA', 'IN_LABORATORIO_INFORMATICA',
                 'IN_QUADRA_ESPORTES_COBERTA', 'IN_QUADRA_ESPORTES_DESCOBERTA', 'IN_INTERNET_ALUNOS',
                 'IN_INTERNET_ADMINISTRATIVO', 'IN_INTERNET_APRENDIZAGEM', 'IN_ACESSO_INTERNET_COMPUTADOR',
                 'IN_ACES_INTERNET_DISP_PESSOAIS', 'IN_ALIMENTACAO', 'IN_LIXO_SERVICO_COLETA', 'IN_LIXO_QUEIMA',
                 'IN_LIXO_ENTERRA', 'IN_LIXO_DESTINO_FINAL_PUBLICO', 'IN_LIXO_DESCARTA_OUTRA_AREA',
                 'IN_TRATAMENTO_LIXO_SEPARACAO', 'IN_TRATAMENTO_LIXO_REUTILIZA', 'IN_TRATAMENTO_LIXO_RECICLAGEM',
                 'IN_TRATAMENTO_LIXO_INEXISTENTE', 'IN_PATIO_COBERTO', 'IN_PATIO_DESCOBERTO', 'IN_REFEITORIO',
                 'IN_SALA_MULTIUSO', 'IN_SALA_DIRETORIA', 'IN_SALA_PROFESSOR', 'IN_SECRETARIA',
                 'IN_ACESSIBILIDADE_CORRIMAO', 'IN_ACESSIBILIDADE_ELEVADOR', 'IN_ACESSIBILIDADE_PISOS_TATEIS',
                 'IN_ACESSIBILIDADE_VAO_LIVRE', 'IN_ACESSIBILIDADE_RAMPAS', 'IN_ACESSIBILIDADE_SINAL_SONORO',
                 'IN_ACESSIBILIDADE_SINAL_TATIL', 'IN_ACESSIBILIDADE_SINAL_VISUAL', 'IN_ACESSIBILIDADE_INEXISTENTE',
                 'IN_COMPUTADOR', 'IN_EQUIP_COPIADORA', 'IN_EQUIP_IMPRESSORA', 'IN_EQUIP_TV',
                 'IN_EQUIP_MULTIMIDIA', 'IN_DESKTOP_ALUNO', 'IN_COMP_PORTATIL_ALUNO', 'IN_TABLET_ALUNO', 'QT_MAT_FUND_AF',
                 'QT_MAT_MED'],
        sep=';', encoding='latin-1'
    )
